[theme]
base = "dark"
primaryColor = "#EC4899"
backgroundColor = "#0F0C20"
secondaryBackgroundColor = "#1A1535"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
